model:
  architecture: VanillaRNN
  neurons: 50
  activation: relu
  seed: 7
  rnn_kwargs: 

training:
  loss: 'cosine'
  clip_value: None
  lr: 0.05
  weight_decay: 0.01
  epochs: 2


task:
  dim: 1
  batch_size: 1
  min_length: 1000
  max_length: 1500
  sample_length: True
  test_batch_size: 200


